version: '2'
services:
  headless-client:
    build: dependencies/headless-client
    links:
      - redis
      - postgres
    environment: &environment
      - TOKEN_APP_SEED=bid wheat idea index crater menu travel almost priority resource breeze patrol
      - TOKEN_APP_USERNAME=SponsorAGrad
      - TOKEN_APP_NAME=Graduate Sponsorship Bot
      - TOKEN_APP_AVATAR=attachments/cap.jpg
      - REDIS_URL=redis://h:rlcMWNrxXgqS0xM8aWCYuE0R@redis:6379
      - DATABASE_URL=postgres://token:va5uOdJBqu2dZ1@postgres:5432/token
      - LOG_LEVEL=INFO
      - ENABLE_LOG_TIMESTAMPS=0
    volumes:
      - ./config/docker.yml:/usr/src/headless-client/config.yml
      - ./attachments:/usr/src/headless-client/attachments
  bot:
    build: .
    links:
      - redis
      - postgres
    environment: *environment
    volumes:
      - ./config/docker.yml:/usr/src/bot/config.yml
      - ./src:/usr/src/bot/src
  redis:
    build: dependencies/redis
    ports:
      - 6379
  postgres:
    image: postgres:9.6
    ports:
      - 15432
    environment:
      - POSTGRES_PASSWORD=va5uOdJBqu2dZ1
      - POSTGRES_USER=token
      - POSTGRES_DB=token
